### PR TITLE
fix module declaration

### LINKED ISSUE #15: apxs:Error: Sorry, cannot determine bootstrap symbol name.
For some reason I get the following error message when using `-i` of apxs:

```
# /usr/local/apache/bin/apxs -i -c mod_authnz_pam.c -lpam -Wall -pedantic
/usr/lib64/apr-1/build/libtool --silent --mode=compile gcc -prefer-pic   -DLINUX -D_REENTRANT -D_GNU_SOURCE  -I/usr/local/apache/include  -I/usr/include/apr-1   -I/usr/include/apr-1   -c -o mod_authnz_pam.lo mod_authnz_pam.c && touch mod_authnz_pam.slo
/usr/lib64/apr-1/build/libtool --silent --mode=link gcc    -o mod_authnz_pam.la  -rpath /usr/local/apache/modules -module -avoid-version    mod_authnz_pam.lo -lpam -Wall -pedantic
apxs:Error: Sorry, cannot determine bootstrap symbol name.
apxs:Error: Please specify one with option `-n'.
```

I believe the way the module is declared within the code is incorrect. I'll send a PR.

### PR DESCRIPTION
**Pull request by tessus**
fixes #15 

Update: If you check other modules (if you are allowed to do that - I wasn't when I was working for IBM due to code contamination issues), you'll see that the declaration should be done differently.

There's also Nick Kew's book on Apache modules.

### CODE REVIEW

File: mod_authnz_pam.c [hunk 1]
```diff
@@ -32,6 +32,8 @@
 
 #include "mod_auth.h"
 
+module AP_MODULE_DECLARE_DATA authnz_pam_module;
```
Comment (adelton) [inline mod_authnz_pam.c:35]: This already exists on line 169.

File: mod_authnz_pam.c [hunk 2]
```diff
@@ -343,12 +345,7 @@ static void register_hooks(apr_pool_t * p) {
 #endif
 }
 
-#ifdef AP_DECLARE_MODULE
-AP_DECLARE_MODULE(authnz_pam)
-#else
-module AP_MODULE_DECLARE_DATA authnz_pam_module
-#endif
-	= {
+AP_DECLARE_MODULE(authnz_pam) = {
```
Comment (adelton) [inline mod_authnz_pam.c:346]: It is true that by now we can assume Apache 2.4+ everywhere, so the `#ifdef` approach is no longer needed.

**Comment by adelton** [comment]
I also filed https://github.com/apache/httpd/pull/359 to get `apxs` fixed to correctly fallback to guessing the module name based on the filename, as the man page suggests it would do.

File: mod_authnz_pam.c (hunk 1 above)
Comment (tessus) [reply mod_authnz_pam.c:35]: I missed that one on line 169, but afaik it has to be the first thing after the includes. So we should delete the one on 169 and keep the one I added.

You can test it, but the ifdef will basically always be `AP_DECLARE_MODULE` unless you use an ancient Apache version, yet apxs still wasn't able to find the module name even with line 169. But if you move it to the beginning, it works.

I've removed line 169 and pushed another commit. I am way past my bedtime, so I'm heading to bed now.

If you play around with my changes, you will see that `apxs -i` works now.

File: mod_authnz_pam.c (hunk 2 above)
Comment (tessus) [reply mod_authnz_pam.c:346]: I think the `AP_DECLARE_MODULE` even existed in 2.2.x. Not sure about 2.0.x though. But what I could gather from other modules, using both is perfectly valid and is done in most modules. Otherwise the `-n` flag is used in the Makefile to install the module via apxs.

**Comment by tessus** [comment]
It's up to you whether you want to merge this. I think that it certainly wouldn't hurt.

File: mod_authnz_pam.c (hunk 2 above)
Comment (adelton) [reply mod_authnz_pam.c:346]: No, it got added in 2.3.6: https://nightlies.apache.org/httpd/trunk/doxygen/group__APACHE__CORE__CONFIG.html#ga662f6bc4b401d52b293a80b1768534af.

File: mod_authnz_pam.c (hunk 1 above)
Comment (adelton) [reply mod_authnz_pam.c:35]: > afaik it has to be the first thing after the includes

It does not. Why should it? It's just a C.

I mean, it does not hurt to move it up but I'm concerned that you use wrong rationales.

> yet apxs still wasn't able to find the module name even with line 169

It's because the regexp
```
$content =~ m|.*AP_DECLARE_MODULE\s*\(\s*([a-zA-Z0-9_]+)\s*\)\s*=.*|s || $content =~ m|.*module\s+(?:AP_MODULE_DECLARE_DATA\s+)?([a-zA-Z0-9_]+)_module\s*=\s*.*|s
```
in https://github.com/apache/httpd/blob/trunk/support/apxs.in#L534 looks for an equal sign after the `AP_DECLARE_MODULE()` so it is the intervening `#else ... #endif` that stops it from working. It has nothing to do with the declaration on line 169 or anywhere you might move it -- that `module AP_MODULE_DECLARE_DATA authnz_pam_module;` is not what matches, no matter where you put it.

> But if you move it to the beginning, it works

It does not, unless you remove the `#ifdef ... #endif` construct as well.

Comment (adelton) [reply mod_authnz_pam.c:35]: > I've removed line 169 and pushed another commit.

Thanks. Can you please squash the commits to one and use some more descriptive commit message, something like "Addressing apxs:Error: Sorry, cannot determine bootstrap symbol name with apxs -i."?

Comment (tessus) [reply mod_authnz_pam.c:35]: > I mean, it does not hurt to move it up but I'm concerned that you use wrong rationales.

Yes, you are right. I came across a few weird compiler issues and optimization errors a while back and it was late, I mixed up few things. My bad.

> looks for an equal sign after the AP_DECLARE_MODULE

Yep, I saw that when I clicked the link to your PR for apxs. I read it after I replied in this thread. ;-)

> Can you please squash the commits to one and use some more descriptive commit message

Will do in a bit.

**Comment by tessus** [comment]
done

**Comment by adelton** [comment]
Perfect, thanks.
